server:
  port: 8080

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaomage2/springcloud-config.git
          username: xiaomage2
          password: ning159753